import type { CollagePhoto } from "../types";

export const TEAM_COLLAGE_PHOTOS: CollagePhoto[] = [
  {
    id: "office-lunch",
    src: "/images/careers/team-photo-1.webp",
    alt: "Teammates sharing a meal around the table in the office",
    leftCqw: 10,
    topCqw: 3,
    widthCqw: 14,
    heightCqw: 18.67,
    rotationDeg: -1.5,
    baseZ: 4,
  },
  {
    id: "work-session",
    src: "/images/careers/team-photo-4.webp",
    alt: "Teammates gathered around a table during a work session",
    leftCqw: 23,
    topCqw: 1,
    widthCqw: 27,
    heightCqw: 20.25,
    rotationDeg: 0,
    baseZ: 2,
  },
  {
    id: "sunset-photo",
    src: "/images/careers/team-photo-2.webp",
    alt: "Teammates photographing a sunset over the skyline from the office",
    leftCqw: 78,
    topCqw: 8,
    widthCqw: 13,
    heightCqw: 17.33,
    rotationDeg: 1.5,
    baseZ: 5,
  },
  {
    id: "skyline-dinner",
    src: "/images/careers/team-photo-7.webp",
    alt: "Three teammates at dinner with the city skyline lit up at night",
    leftCqw: 10,
    topCqw: 20,
    widthCqw: 24,
    heightCqw: 18,
    rotationDeg: 0,
    baseZ: 3,
  },
  {
    id: "rooftop-dinner",
    src: "/images/careers/team-photo-3.webp",
    alt: "The team having dinner together at a rooftop restaurant",
    leftCqw: 46,
    topCqw: 14,
    widthCqw: 36,
    heightCqw: 27,
    rotationDeg: 0,
    baseZ: 1,
  },
  {
    id: "elevator-group",
    src: "/images/careers/team-photo-6.webp",
    alt: "The team crowded together for a group photo in an elevator",
    leftCqw: 78,
    topCqw: 34,
    widthCqw: 13,
    heightCqw: 17.33,
    rotationDeg: 0,
    baseZ: 6,
  },
  {
    id: "office-dog",
    src: "/images/careers/team-photo-8.webp",
    alt: "The office dog dressed up in a bandana and hair bow",
    leftCqw: 16,
    topCqw: 34,
    widthCqw: 14,
    heightCqw: 18.67,
    rotationDeg: -1,
    baseZ: 8,
  },
  {
    id: "couch-with-dog",
    src: "/images/careers/team-photo-5.webp",
    alt: "Two teammates working on the office couch with a dog",
    leftCqw: 35,
    topCqw: 33,
    widthCqw: 25,
    heightCqw: 18.75,
    rotationDeg: 0,
    baseZ: 7,
  },
];

export const TEAM_COLLAGE_CONTAINER_ASPECT = "2000/1100";
